apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: audio-us-discord-bot
  labels:
    cloud.googleapis.com/location: asia-southeast1
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/allow-unauthenticated: "true"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 3600
      serviceAccountName: 719882175475-compute@developer.gserviceaccount.com
      containers:
      - name: audio-us-discord-bot
        image: asia-southeast1-docker.pkg.dev/thesis21kdl/audio-us-discord-bot/audio-us-discord-bot:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: audio-us-discord-bot-token
              key: latest
        - name: API_SERVER_URL
          value: "https://audio-us-model-719882175475.asia-southeast1.run.app"
        - name: USE_HOST
          value: "true"
        - name: NGROK_TOKEN
          value: ""
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true