apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: audio-us-backend
  labels:
    cloud.googleapis.com/location: asia-southeast1
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/allow-unauthenticated: "false"
    spec:
      containerConcurrency: 50
      timeoutSeconds: 120
      serviceAccountName: 719882175475-compute@developer.gserviceaccount.com
      containers:
      - name: audio-us-backend-api
        image: asia-southeast1-docker.pkg.dev/thesis21kdl/audio-us-backend/audio-us-backend:latest
        ports:
        - name: http1
          containerPort: 6065
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 6065
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
  traffic:
  - percent: 100
    latestRevision: true
