CREATE TABLE user_info (
    id SERIAL PRIMARY KEY,
    discord_id VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(255),
    username VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 